# BitKnotsRS Regtest Configuration
# Bitcoin regtest settings for local development and testing

[network]
network = "regtest"
datadir = "./data/regtest"

[api]
host = "127.0.0.1"
port = 8332
enabled = true
cors_enabled = true

[api.rate_limit]
requests_per_minute = 1000
burst_size = 50

[rpc]
host = "127.0.0.1"
port = 18443
user = "regtest"
password = "regtest"
enabled = true
allowed_methods = [
    "getblockchaininfo",
    "getbestblockhash",
    "getblock",
    "gettransaction",
    "sendrawtransaction",
    "getmempoolinfo",
    "getrawmempool",
    "getpeerinfo",
    "getnetworkinfo",
    "generate",
    "generatetoaddress"
]

[storage]
rocks_db_path = "./data/regtest/rocksdb"
cache_size = 268435456  # 256MB
max_open_files = 500
compression = "lz4"
backup_enabled = false
backup_interval_hours = 24

[network_config]
listen_port = 18444
max_peers = 8
connection_timeout_secs = 10
discovery_interval_secs = 30
custom_peers = ["127.0.0.1:18444", "localhost:18444"]
enable_dns_seeds = false
enable_peer_exchange = true

[network_config.zmq]
enabled = true
pub_port = 28332
sub_endpoints = []
topics = ["hashblock", "hashtx", "rawblock", "rawtx"]

[metrics]
enabled = true
host = "127.0.0.1"
port = 9090
path = "/metrics"

[metrics.otel]
enabled = false
endpoint = ""
service_name = "bitknotsrs-regtest"
service_version = "0.1.0"

[logging]
level = "debug"
format = "pretty"
file_enabled = true
file_path = "./logs/regtest/bitknotsrs.log"
max_file_size_mb = 10
max_files = 3

[events]
enabled_publishers = ["zmq"]

[events.zmq]
enabled = true
port = 28333
topics = ["block", "transaction", "peer"]

[events.k8s]
enabled = false
namespace = "bitcoin-regtest"
node_name = "bitknotsrs-regtest"
event_types = ["block", "transaction", "peer", "chain"]

[events.webhook]
enabled = false
endpoints = []
timeout_secs = 5
retry_attempts = 1